### ISSUE TITLE
Getting better result with svr regression

### ISSUE THREAD

**Issue by SamuelLachance** [silasnevstad/NHL3.0#3]
![image](https://user-images.githubusercontent.com/26681678/224726817-e0ec5639-13c8-451e-a7bf-183552d5287c.png)
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVR

# ---- Build Models -----

ridge_home_gf = SVR(kernel='rbf', C=1e3, gamma='scale') #Ridge(alpha = 1.0) # create the model (goals for)
ridge_home_ga = SVR(kernel='rbf', C=1e3, gamma='scale') #Ridge(alpha = 1.0) # create the model (goals against)

ridge_away_gf = SVR(kernel='rbf', C=1e3, gamma='scale') #Ridge(alpha = 1.0) create the model (goals for)
ridge_away_ga = SVR(kernel='rbf', C=1e3, gamma='scale') #Ridge(alpha = 1.0) # create the model (goals against)

**Comment by silasnevstad** [comment]
What were you getting from Ridge Regression; because when I ran it, I got this:
![Screenshot 2023-03-13 at 6 44 13 PM](https://user-images.githubusercontent.com/115965493/224849021-42c8fc33-6e49-4909-9135-34fedc05959c.png)

**Comment by SamuelLachance** [comment]
damm i was getting way worst than that , idk why . Also i have another question poisson distribution take in count the draw , but there is no draw in hockey . Anything we can do about it ?

**Comment by SamuelLachance** [comment]
![image](https://user-images.githubusercontent.com/26681678/225141207-fdfbab6d-ffce-4fb2-bd22-2b25fb3d92f6.png)

when i use ridgre regression .. idk what i'm doing wrong

**Comment by SamuelLachance** [comment]
is the code on your github your last updated one ? maybe i run an older version

**Comment by silasnevstad** [comment]
> damm i was getting way worst than that , idk why . Also i have another question poisson distribution take in count the draw , but there is no draw in hockey . Anything we can do about it ?

Hmm, that is weird. As for the ties, we could not calculate them in the loop; however, I don't think this would make much of a difference. Currently, it adds half of the draw likelihood to each team's win prob. Also, most ML bets are only for regulation time, meaning there sort of is a draw, in terms of betting at least.

**Comment by silasnevstad** [comment]
> is the code on your github your last updated one ? maybe i run an older version

I have made some recent changes, but nothing with the ridge model, I don't think. I can push my latest updates later tonight.

**Comment by SamuelLachance** [comment]
please , ty .
